config/routes.rb
Rails.application.routes.draw do
  resources :gestors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'gestor#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gestor.rb
class Gestor < ApplicationRecord
    validates :nombre, :descripcion, :estado, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gestors_controller.rb
class GestorsController < ApplicationController
  before_action :set_gestor, only: %i[ show edit update destroy ]

  # GET /gestors or /gestors.json
  def index
    #@gestors = Gestor.all
    if params[:state].present?
      @gestors = Gestor.where('state=?', params[:state])
    else 
      @gestors = Gestor.all
    end
  end

  # GET /gestors/1 or /gestors/1.json
  def show
  end

  # GET /gestors/new
  def new
    @gestor = Gestor.new
  end

  # GET /gestors/1/edit
  def edit
  end

  # POST /gestors or /gestors.json
  def create
    @gestor = Gestor.new(gestor_params)

    respond_to do |format|
      if @gestor.save
        format.html { redirect_to gestor_url(@gestor), notice: "Gestor was successfully created." }
        format.json { render :show, status: :created, location: @gestor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gestor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gestors/1 or /gestors/1.json
  def update
    respond_to do |format|
      if @gestor.update(gestor_params)
        format.html { redirect_to gestor_url(@gestor), notice: "Gestor was successfully updated." }
        format.json { render :show, status: :ok, location: @gestor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gestor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gestors/1 or /gestors/1.json
  def destroy
    @gestor.destroy

    respond_to do |format|
      format.html { redirect_to gestors_url, notice: "Gestor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gestor
      @gestor = Gestor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gestor_params
      params.require(:gestor).permit(:nombre, :descripcion, :fecha_inicio, :fecha_termino, :estado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gestors_helper.rb
module GestorsHelper
end

app/views/gestors/_form.html.erb
<%= form_with(model: gestor) do |form| %>
  <% if gestor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gestor.errors.count, "error") %> prohibited this gestor from being saved:</h2>

      <ul>
        <% gestor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :fecha_inicio, style: "display: block" %>
    <%= form.date_field :fecha_inicio %>
  </div>

  <div>
    <%= form.label :fecha_termino, style: "display: block" %>
    <%= form.date_field :fecha_termino %>
  </div>

  <div>
   Estado del proyecto: 
    <select <%= form.text_field :estado %> >
                  <option value=""> </option>
                  <option value="propuesta">Propuesta</option>
                  <option value="en progreso">En progreso</option>
                  <option value="terminado">Terminado</option>
    </select>
    <%= form.label :estado, style: "display: block" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gestors/_gestor.html.erb
<div id="<%= dom_id gestor %>">
  <p>
    <strong>Nombre:</strong>
    <%= gestor.nombre %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= gestor.descripcion %>
  </p>

  <p>
    <strong>Fecha inicio:</strong>
    <%= gestor.fecha_inicio %>
  </p>

  <p>
    <strong>Fecha termino:</strong>
    <%= gestor.fecha_termino %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= gestor.estado %>
  </p>

</div>

app/views/gestors/edit.html.erb
<h1>Editing gestor</h1>

<%= render "form", gestor: @gestor %>

<br>

<div>
  <%= link_to "Show this gestor", @gestor %> |
  <%= link_to "Back to gestors", gestors_path %>
</div>

app/views/gestors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gestor</h1>


<!--Formulario para buscar proyectos de acuerdo al estado-->
<form class="form-inline">
      Buscar proyectos por estado: 
    <select name="estado"  >
                  <option value="">Estado</option>
                  <option value="propuesta">Propuesta</option>
                  <option value="en progreso">En progreso</option>
                  <option value="terminado">Terminado</option>
    </select>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>


<%= link_to "New gestor", new_gestor_path %>

<div id="gestors">
  <% @gestors.each do |gestor| %>
    <%= render gestor %>
    <p>
      <%= link_to "Show this gestor", gestor %>
    </p>
  <% end %>
</div>

app/views/gestors/new.html.erb
<h1>New gestor</h1>

<%= render "form", gestor: @gestor %>

<br>

<div>
  <%= link_to "Back to gestors", gestors_path %>
</div>

app/views/gestors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gestor %>

<div>
  <%= link_to "Edit this gestor", edit_gestor_path(@gestor) %> |
  <%= link_to "Back to gestors", gestors_path %>

  <%= button_to "Destroy this gestor", @gestor, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorProyectos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>